root@ansible:/etc/ansible# cat root_password_change2.yml
---
- name: Update root password
  hosts: test
  become: true
  become_method: sudo
  vars:
    root_password: "Qwerty^54321" # set the new password here
    ansible_become_password: act@369$
  tasks:
    - name: Update root password
      user:
        name: root
        password: "{{ root_password | password_hash('sha512') }}"
root@ansible:/etc/ansible#
